### ISSUE TITLE
Improve contact us layout

### ISSUE THREAD

**Issue by jukecraft** [codurance/site#498] opened 2017-01-05 15:44 UTC
when loading the "contact us" part of a page, the map is not visible until it's completely loaded. That space stays blank and makes the layout look weird. And to fill in the fields, the user has to move focus to the right.

I suggest switching the map to the right side to help with this. 

![screen shot 2017-01-05 at 15 41 46](https://cloud.githubusercontent.com/assets/5154737/21686492/8a9566ce-d35d-11e6-841b-dfbec6214dd1.png)

**Comment by neomatrix369** [comment] 2017-01-09 13:44
I haven't been able to easily spot the Contact Us page, has this been temporarily removed or hidden?

**Comment by neomatrix369** [comment] 2017-01-09 16:15
Found it under https://codurance.com/company/

**Comment by lpalma** [comment] 2018-02-10 18:04
Since the map is at the bottom of the `/company` page, by the time we scroll down to visualize it, it has already been fully loaded.

I can't reproduce this issue and it's over a year old, so I'm closing it down.

**Closed as completed by lpalma** 2018-02-10 18:04 UTC
Labels: page-layout
