### ISSUE TITLE
Files in AWS are not deleted when removed from the repo.

### ISSUE THREAD

**Issue by keith-smale** [codurance/site#1491] opened 2019-10-21 13:50 UTC
When images of people who have left the company are removed from the repo and that is pushed, the actual image file doesn't seem to be removed in AWS.

This may also be the same for other files (not just images) in the repo.

Christina R took a look at the commands we use to deploy a new version of the site and a tag --delete could be added to remove any files that are deleted.

**Comment by jaramir** [comment] 2019-10-21 14:36
duplicate of #1383

**Closed as completed** 2020-02-21 15:10 UTC
